### ISSUE TITLE
TCP binding issues when using parallel deployment

### ISSUE THREAD

**Issue by ahfeel** [deployphp/deployer#1021]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | OSX
| Remote Machine OS | Linux

### Description 
Getting TCP binding issues when using parallel deployment. I'm using native ssh_type and ssh_multiplexing true.

### Content of `deploy.php`
```php
<?php

namespace Deployer;

require 'recipe/common.php';

set('ssh_type', 'native');
set('ssh_multiplexing', true);
set('allow_anonymous_stats', false);

serverList('serverlist.yml');

task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');
after('deploy', 'success');

```

### Output log
$ ./deployer.phar -p deploy prod
✘ Could not bind to tcp://127.0.0.1:3333: Address already in use
✘ Could not bind to tcp://127.0.0.1:3334: Address already in use
✔ Executing task ....

**Comment by elfet** [comment]
This means what bg workers is still alive. I think we need docs here.

**Comment by antonmedv** [comment]
Completely fixed in #1092. Will never appear again.

**Comment by pvanhemmen** [comment]
I still get this error with deployer v4.3.0 with parallel deployment. Deployment fails during the composer install routine.

Manually triggering composer install / composer update in the release folder on the server does not lead to any errors.

Anything I can to to fix this or to help fixing it?

**Comment by antonmedv** [comment]
This error fixed in v5.
