### ISSUE TITLE
404 returned when trying to download phar archive

### ISSUE THREAD

**Issue by acelaya** [deployphp/deployer#142]
Link provided in website to download the phar archive returns a 404 http://deployer.org/deployer.phar

Composer also throws an error when trying to install it from dist, but is able to install it from sources.

**Comment by elfet** [comment]
Yeah, sorry about that, moving repository right now.

**Comment by vanchelo** [comment]
I cant download too =(

**Comment by elfet** [comment]
Sorry again! Wait until evening! :sweat: Working :sweat_drops:

**Comment by AlexStansfield** [comment]
I noticed the release last night 2.0.1 doesn't have a phar file. I tried to build myself but get:
PHP Fatal error:  Class 'Net_SFTP' not found in phar:///tmp/deployer-2.0.1/deployer.phar/src/Server/PhpSecLib.php on line 28

If i try to run the bin/dep I get the same:
PHP Fatal error:  Class 'Net_SFTP' not found in /tmp/deployer-2.0.1/src/Server/PhpSecLib.php on line 28

Is this a bug with the PhpSecLib stuff? I'm giving a talk to the Thailand PHP User's group next week about deployer but really could do with there being a working phar file.

**Comment by elfet** [comment]
Do you run `composer install`? :smile: 

I builded 2.01 phar my self: [v2.0.1](https://github.com/deployphp/deployer/releases/tag/v2.0.1)

Now developing Phar-channel for deployer with auto-update, stable and dev-master channels. 

>  I'm giving a talk to the Thailand PHP User's group next week about deployer but really could do with there being a working phar file. 

Cool! If you could share slides or video after event will be great! 

Also you could show Deployer 3, which will be 200% awesome :trophy: (parallel deployment `dep deploy --parallel`)

**Comment by AlexStansfield** [comment]
I did run composer install, it won't build without it.

I just downloaded your build and ran it:
$ php deployer.phar deploy
Preparing server for deploy.................................PHP Fatal error:  Class 'Net_SFTP' not found in phar:///vagrant_data/deployment/smartnavigator/deployer.phar/src/Server/PhpSecLib.php on line 28

Same error as I get.

I don't think I'll have time to show Deployer 3. It's just a short talk, but will share any slides I have from it.

**Comment by elfet** [comment]
Hmmm, a think a get error, will fix it right now. (PhpSecLib :disappointed:)

PS You can always install php extension ssh2 which is very cool.

**Comment by AlexStansfield** [comment]
It's the namespaces, they have changed in the latest version:

e.g 
new \Net_SFTP($this->config->getHost(), $this->config->getPort())
should be
new new \phpseclib\Net\SFTP($this->config->getHost(), $this->config->getPort());

I'm aware of the php ssh2 extension but I'm looking for an entire php solution, so I can put the phar on any computer with a php interpreter and deploy stuff. Also we use PEM key files which as far as I'm aware the ssh2 extension doesn't support.

**Comment by elfet** [comment]
Yeah, PEM files. Also working of implementation of PEM support for php-ssh2.

**Comment by elfet** [comment]
Fixed, [v2.0.1](https://github.com/deployphp/deployer/releases/tag/v2.0.1)

**Comment by AlexStansfield** [comment]
Great, thanks

**Comment by AlexStansfield** [comment]
Did you rebuild the phar? The source looks fixed, but the phar you offer is still broken.

**Comment by elfet** [comment]
Sorry, it was old one. Now must be ok.

**Comment by AlexStansfield** [comment]
Great, can confirm it's working :)

**Comment by elfet** [comment]
:sweat_smile: :dash:
