### ISSUE TITLE
Empty RuntimeException on "Installing vendors" task

### ISSUE THREAD

**Issue by oRastor** [deployphp/deployer#201]
I've tried running deployment process today and got empty RuntimeException on "Installing vendors" task. 
```
Installing vendors
Run task deploy:vendors on server main
[***.***.***.***] cd /var/www/releases/2015022645728 && if [ -e /var/www/releases/2015022645728/composer.phar ]; then echo 'true'; fi
[***.***.***.***] :: 
[***.***.***.***] cd /var/www/releases/2015022645728 && curl -s http://getcomposer.org/installer | php
[***.***.***.***] :: #!/usr/bin/env php
[***.***.***.***] :: All settings correct for using Composer
[***.***.***.***] :: Downloading...
[***.***.***.***] :: 
[***.***.***.***] :: Composer successfully installed to: /var/www/releases/2015022645728/composer.phar
[***.***.***.***] :: Use it: php composer.phar
[***.***.***.***] :: 
[***.***.***.***] cd /var/www/releases/2015022645728 && php composer.phar install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress
Run task deploy:rollback on server main
Rolling back to previous release on server main
[***.***.***.***] cd /var/www && rm -rf /var/www/releases/2015022645728
[***.***.***.***] :: 


                                                           
  [RuntimeException]                                       
  Loading composer repositories with package information   
  Installing dependencies from lock file                   
    - Installing react/promise (v2.2.0)                    
      Loading from cache                                   
      Extracting archive                                   
    - Installing guzzlehttp/streams (3.0.0)                
      Loading from cache                                   
      Extracting archive                                   
    - Installing guzzlehttp/ringphp (1.0.5)                
      Loading from cache                                   
      Extracting archive                                   
    - Installing guzzlehttp/guzzle (5.2.0)                 
      Loading from cache                                   
      Extracting archive                                   
...
    - Installing symfony/console (v2.6.4)                  
      Loading from cache                                   
      Extracting archive                                   
  Generating optimized autoload files                      
                                                           


Exception trace:
 () at phar:///usr/local/bin/dep/vendor/herzult/php-ssh/src/Ssh/Exec.php:28
 Ssh\Exec->run() at phar:///usr/local/bin/dep/src/Server/Ssh2.php:94
 Deployer\Server\Ssh2->run() at phar:///usr/local/bin/dep/src/functions.php:115
 run() at /var/www/cs-cp-deploy/vendor/boomers/deployer-recipes/src/default.php:166
 {closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Runner.php:45
 Deployer\Task\Runner->run() at phar:///usr/local/bin/dep/src/Console/RunTaskCommand.php:168
 Deployer\Console\RunTaskCommand->runSeries() at phar:///usr/local/bin/dep/src/Console/RunTaskCommand.php:118
 Deployer\Console\RunTaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:114
 Deployer\Deployer->run() at phar:///usr/local/bin/dep/bin/dep:51
 require() at /usr/local/bin/dep:4
```

But this command ```php composer.phar install --no-dev --verbose --prefer-dist --optimize-autoloader --no-progress``` works fine without deployer.
Deployer version: 2.0.2

**Comment by onesvat** [comment]
Same problem here.

Thanks.

**Comment by elfet** [comment]
I think it's because of update of Composer. Already have PR #199 
Update Deployer version: `dep self-update`.

**Comment by onesvat** [comment]
dep self-update did not give last version. I tried to manually build v2.0.5, but it failed to build.  I managed to build this version : https://github.com/guru-digital/deployer/tree/f7f51db6f32a5bc54029d738bf79a7da5b5b0d17 and it worked. I think there is a problem v2.0.5

**Comment by elfet** [comment]
Try to download Deployer here: http://deployer.org/deployer.phar

**Comment by ceesvanegmond** [comment]
I've updated deployer to 2.0.5 and I experience the same problem. The .phar @elfet proved is a 404. What to do now?

**Comment by elfet** [comment]
Fixed.

**Comment by cmodijk** [comment]
How is it fixed? We installed deployer 2.0.5 using composer and we are still getting the same error.

**Comment by elfet** [comment]
Does latest v2.0.5 does not working? It must be fixed via PR #199

**Comment by ceesvanegmond** [comment]
Unfortunately not, we're getting (still) the same error.

**Comment by elfet** [comment]
Try to do this composer.json:
```json
{
    "require": {
        "deployer/deployer": "2.0.5"
    },
    "provide": {
        "ext-ssh2": "*"
    },
    "minimum-stability": "dev"
}
```

**Comment by cmodijk** [comment]
@elfet I see that the fix is done inside the PhpSecLib class but the Ssh\Exec class is trowing the exception. 
https://github.com/Herzult/php-ssh/blob/master/src/Ssh/Exec.php#L28

**Comment by cmodijk** [comment]
If I set `set('use_ssh2', false);` then it works so it's fixed for the PhpSecLib server type and not the SSH2 server type

**Comment by elfet** [comment]
Yeaah. A bug of php-ssh lib. Can you create in there?

**Comment by cmodijk** [comment]
Done!

**Comment by elfet** [comment]
Cool! Thanks!
