### ISSUE TITLE
get('branch') returns incorrect branch when run within a locally run task

### ISSUE THREAD

**Issue by mattsimpson** [deployphp/deployer#2133]
**Describe the bug**
If you have set a branch within a stage by using  `->set('branch', 'develop')`, the branch is ignored completely for tasks set to run locally.

**To reproduce**
1. Copy the contents of `deploy.php` below.
2. Run `dep deploy staging`.

**Actual behavior**
➤ Executing task branch:name
Branch develop
➤ Executing task branch:localname
Branch master

**Expected behavior**
➤ Executing task branch:name
Branch develop
➤ Executing task branch:localname
Branch develop

**Environment**
* Deployer version: v6.8.0
* PHP version: v7.3.20
* Deployment target(s) OS: CentOS 7

**Content of `deploy.php`**
```php
<?php
namespace Deployer;

require 'recipe/common.php';

set('allow_anonymous_stats', false);

set('branch', 'master'); // Default branch

host('staging')
    ->set('branch', 'develop')
    ->set('deploy_path', '/var/www/html');

task('branch:name', function() {
    writeln('Branch ' . get('branch'));
});

task('branch:localname', function() {
    writeln('Branch ' . get('branch'));
})->local();

desc('Deploy your branch bug report.');
task('deploy', [
    'branch:name',
    'branch:localname'
]);
```

**Output log with enabled option for verbose output `-vvv`**
```sh
$ dep deploy staging -vvv
➤ Executing task branch:name
Branch develop
• done on [staging]
✔ Ok [0ms]
➤ Executing task branch:localname
Branch master
✔ Ok [0ms]
```

**Comment by mattsimpson** [comment]
@antonmedv I tried pretty hard to fix this in Deployer and I really wanted to submit a PR for it. Unfortunately, I couldn't find the right fix. My immediate workaround was do the following (see below) and use `{{stage_branch}}` instead of `{{branch}}` within my `local()` tasks. We are totally willing to pay for the right fix to Deployer. Perhaps a v6.8.1?

```
set('stage_branch', function () {
    $selectedStage = input()->getArgument('stage');

    foreach (Deployer::get()->hosts as $host) {
        if ($host->get('stage') == $selectedStage) {
            return (string)$host->get('branch', get('branch'));
        } else {
            continue;
        }
    }
});
```

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).

**Comment by mbrodala** [comment]
@antonmedv Can you explain how this is supposed to work with v7? I still see the same issue that any local task runs on a `Localhost` instance with no relation to actually selected `Host` instances. Thus the branch of a host can still not be used for local tasks ...

**Comment by antonmedv** [comment]
Currently there’s idea to depreciate local tasks completely. There is a good replacement: runLocally

**Comment by mbrodala** [comment]
That's true but you cannot run predefined task using `runLocally()`. For that you need to use `invoke()` either in a wrapping task marked as `->local()` or by using `on(localhost(), ...)` instead. So that's not really a solution I'm afraid.

**Comment by mbrodala** [comment]
Our workaround ATM is to manually forward the `branch` from the selected host to locally invoked tasks:

```php
task('build', function (): void {
    $branch = get('branch'); // Get "branch" from selected host

    on(localhost(), function () use ($branch): void {
        set('branch', $branch); // Set "branch" on localhost
        invoke('deploy:update_code'); // Make use of "branch"
    });
});
```

**Comment by antonmedv** [comment]
Got it. So this is good please to improve before v7. Can you please tell me more about your setup and how do use deployer.

**Comment by mbrodala** [comment]
We basically use the "build server" strategy indicated here: https://deployer.org/docs/advanced/deploy-strategies.html#build-server

Thus most of our deployment workflow happens locally. The basic workflow:

1. Set up directory structure (remote)
2. Lock deployment (remote)
3. Set up directory structure (local)
4. Clone Git repository by branch (local)
5. Install Composer dependencies (local)
6. Install frontend dependencies (local)
7. Build frontend assets (local)
8. Upload release to remote server (local -> remote)
9. Run migrations (remote)
10. Flush caches (remote)
11. Run final tests (remote)
12. Switch release (remote)
13. Cleanup (remote)

Our hosts always `->set('branch', ...)` to clearly dictate their source. This way we can be sure that `dep deploy <host>` will *always* deploy the related branch, no matter the environment where Deployer is invoked. So e.g. we _could_ also add `--branch <branch>` which would be easy within a CI pipeline, but this would lead to unexpected results if a developer invokes Deployer locally and forgets about this. Thus a host must encapsulate everything about itself including its source branch.

**Comment by antonmedv** [comment]
I think I got idea of how to fix it in v7.

**Comment by antonmedv** [comment]
Please, test this PR, it contains a fix: https://github.com/deployphp/deployer/pull/2457

**Comment by antonmedv** [comment]
Fixed!

**Comment by mbrodala** [comment]
Yes, I can confirm that this is working now! Given the following task:

```php
task('test', function (): void {
    writeln(get('branch'));
})->local();
```

Result with beta 13:

```
$ dep test staging
╭──────────────────────────────────────────────────────╮
│                                                      │
│   Update available! https://deployer.org/download/   │
│                                                      │
╰──────────────────────────────────────────────────────╯
task test                                                                                                                                                                                                         
[local] master
```

Result with the latest beta 19 (at least 14):

```
$ dep test staging
task test                                                                                                                                                                                                         
[*staging] staging
```

@antonmedv , thanks a lot!

**Comment by mbrodala** [comment]
The only thing left is a clear explanation/documentation of the "local CI server" pattern.

While the `branch` of a `host()` is now accessible within a `->local()` task, I'm still missing how to `invoke()` predefined tasks like `deploy:update_code` with local options like `deploy_path` and `release_path`. Actually the issue is here that `run()` in a `->local()` task is now executed on the server instead of locally. So far I had the impression that `run()` + `->local()` = `runLocally()`. Of course, I could simply use `runLocally()` for my own tasks but predefined tasks like `deploy:update_code` are fixed to `run()`, so I need to move these into a local host context while still being able to access options from the actual remote host.

My goal is, as indicated above, to have a `build` task which is `->local()` and invokes `deploy:update_code`, `deploy:vendors` and a few other tasks to prepare a release locally. Afterwards this release will be uploaded to the remote host using the `rsync` task.

@antonmedv Can you fill the missing pieces?

**Comment by antonmedv** [comment]
> that run() + ->local() = runLocally(). 

actually this must be true.

**Comment by mbrodala** [comment]
Small correction: it mostly works if I set `deploy_path` and `release_path` inside of my `->local()` task: all predefined tasks invoked here will use this.

But I noticed that the overrides leak into the following, non-local tasks so it looks like the `set()` calls within the `->local()` task affect the `host()` ...

**Comment by antonmedv** [comment]
This is correct, now local tasks only difference in run==runLocally.
