### ISSUE TITLE
`runLocally()` does not respect settings

### ISSUE THREAD

**Issue by coreyworrell** [deployphp/deployer#3136]
- Deployer version: 6.8.0
- Deployment OS: Alpine

**deploy.php**
```php
set('bin/wp', 'wp');

host('user@host')
  ->set('bin/wp', '/path/to/wp');

task('test_wp', function () {
  runLocally('{{bin/wp}} cli info');
});
```
Running `dep test_wp` I would expect `{{bin/wp}}` to resolve to `wp` in this case, but instead it ends up using `/path/to/wp` when running the command on localhost.

The only thing I've found that works so far is

```php
task('test_wp', function () {
  on(localhost(), function () {
      run('{{bin/wp}} cli info');
  });
});
```

**Comment by antonmedv** [comment]
Fixed in v7.

**Comment by coreyworrell** [comment]
@antonmedv Testing with v7 this still appears to be an issue.

```php
set('bin/wp', 'wp');

host('domain.com')
  ->set('bin/wp', '/path/to/wp');

task('test_wp', function (): void {
  runLocally('{{bin/wp}} cli info');
});
```

The `{{bin/wp}}` uses the remote hosts value, and it shows in the log as running on the remote host, but it actually runs on localhost because the remote executable does not exist on localhost:

```
[domain.com]  error  in deploy.php on line 9:
[domain.com] run /path/to/wp cli info
[domain.com] err bash: line 1: /path/to/wp: No such file or directory
[domain.com] exit code 127 (Command not found)
```

**Comment by antonmedv** [comment]
> The {{bin/wp}} uses the remote hosts value,

This is accurate behaviouir

**Comment by coreyworrell** [comment]
@antonmedv you said that it was fixed in v7, so that behavior contradicts what you mentioned previously? If `bin/wp` are different on localhost and remote host, how can I run the local version? I assumed `runLocally()` would run in the context of localhost, not in the remote host context.

**Comment by antonmedv** [comment]
>  I assumed runLocally() would run in the context of localhost, not in the remote host context.

This is no longer true in v7. (it was the case in v6, but caused numerous bugs and confusion). 

Now in v7 runLocally runs in host's context, but executed command locally.

**Comment by coreyworrell** [comment]
@antonmedv okay, so do you have any recommendation for how to accomplish this?

I suppose this could work, but doesn't feel great.

```php
$local_wp = 'wp';

set('bin/wp', $local_wp);

host('domain.com')
  ->set('bin/wp', '/path/to/wp');

task('test_wp', function () use ($local_wp): void {
  runLocally("{$wp} cli info");
});
```

**Comment by antonmedv** [comment]
Your example is ok. Depends on what your try to achieve.

**Comment by coreyworrell** [comment]
@antonmedv here is a more concrete example, our use case of pushing/pulling database to/from localhost to remote.

```php
task('db:push', function (): void {
    runLocally('{{bin/wp}} db export {{local_database_file}}');
    upload('{{local_database_file}}', '{{remote_database_file}}');
    runLocally('rm {{local_database_file}}');

    cd('{{current_path}}');
    run('{{bin/wp}} db import {{remote_database_file}}');
    run('rm {{remote_database_file}}');

    if (get('url') && get('local_url')) {
        run('{{bin/wp}} search-replace {{local_url}} {{url}} --all-tables --precise');
    }
})->desc('Push database');
```

**Comment by antonmedv** [comment]
runLocally('{{local_wp}}
